./configure --with-ssl \
	--with-curses \
	--with-gnutls \
	--with-sasl \
	--with-zlib \
	--with-idn2 \
	--enable-pop \
	--enable-imap \
	--enable-smtp \
	--enable-hcache \
	--prefix=/home/user/opt/mutt/
